### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by ksm200** [MichaelKheel/ProKreedz#1]
I installed the plugin until I converted it to 1.9.0 (5271)
the plugin does not work when opening the server it closes and does not send me the errors

**Comment by MichaelKheel** [comment]
> I installed the plugin until I converted it to 1.9.0 (5271)
> the plugin does not work when opening the server it closes and does not send me the errors

At the moment, the documentation is incomplete and some files are missing. The repository was open to those who needed the source code of the plugin itself. Everything will be posted soon.
