### ISSUE TITLE
CT cannot be selected

### ISSUE THREAD

**Issue by kingsh2012** [MichaelKheel/ProKreedz#10]
Hello, I have encountered a problem, when the [REC] BOT appears, I re-enter the server and cannot automatically select the CT, enter /menu -> 6 prompts "[CC] You can not use mode Noclip"
os:windows10
rehlds:2753
![bkz_goldbhop0002](https://user-images.githubusercontent.com/9623745/161991942-d7b73dd5-d003-485d-b802-a0bf96fac6fc.jpg)
![image](https://user-images.githubusercontent.com/9623745/161992004-23218d6f-f86e-4bf0-b68a-e32ae80c95a7.png)
![image](https://user-images.githubusercontent.com/9623745/161992082-9f77cf34-9d7f-4a1d-a079-4d694146e830.png)
![image](https://user-images.githubusercontent.com/9623745/161992126-4d2ed04b-5dd2-4038-9edf-e1fefdf7aab8.png)

**Comment by MichaelKheel** [comment]
I haven't tested the plugin above amxmodx 1.8.3 version, conflicts are possible.

**Comment by kingsh2012** [comment]
thanks i'll test it
