### ISSUE TITLE
help to install/compile the plugin

### ISSUE THREAD

**Issue by talnaim2323** [MichaelKheel/ProKreedz#3]
> // C:\Users\talna\Desktop\≈Θ÷σ°Θφ ∙Θεσ∙ΘΘφ\amx studio\files\addons\amxmodx\scripting\KZ_Engine.sma(348) : warning 201: redefinition of constant/macro (symbol "Red")
// C:\Users\talna\Desktop\≈Θ÷σ°Θφ ∙Θεσ∙ΘΘφ\amx studio\files\addons\amxmodx\scripting\KZ_Engine.sma(351) : warning 201: redefinition of constant/macro (symbol "Blue")
// C:\Users\talna\Desktop\≈Θ÷σ°Θφ ∙Θεσ∙ΘΘφ\amx studio\files\addons\amxmodx\scripting\KZ_Engine.sma(4284) : error 032: array index out of bounds (variable "g_iColor")
// C:\Users\talna\Desktop\≈Θ÷σ°Θφ ∙Θεσ∙ΘΘφ\amx studio\files\addons\amxmodx\scripting\KZ_Engine.sma(4286) : error 032: array index out of bounds (variable "g_iColor")
// C:\Users\talna\Desktop\≈Θ÷σ°Θφ ∙Θεσ∙ΘΘφ\amx studio\files\addons\amxmodx\scripting\KZ_Engine.sma(5069) : warning 204: symbol is assigned a value that is never used: "mapIsAXN"

i dont know maybe has more..

**Comment by MichaelKheel** [comment]
[colorchat.zip](https://github.com/MichaelKheel/ProKreedz/files/5470758/colorchat.zip)

**Comment by talnaim2323** [comment]
> maybe you have the wrong colorchat
> 
> [colorchat.zip](https://github.com/MichaelKheel/ProKreedz/files/5470758/colorchat.zip)

thanks, i compile it now.
 but in the server its doesnt work any function/commands...
